/* projeto_m_proB
 * Author: Ricar
 * Creation date: 01/06/2019
 */
MACHINE
    projeto_m_proB

SEES projeto_m_ctx
EXTENDS projeto_m

PROPERTIES
    card ( USER ) = 20
    & card ( STORE ) = 5
    & card ( PRODUCT ) = 5
    & card ( PROD_CATEGORY ) = 3
    & card ( ADDRESS ) = 10
    & card ( NAME ) = 5
    & card ( DATE ) = 10
    & card ( DESCRIPTION ) = 100
    & card ( COLOR ) = 10
    & card ( IMAGE ) = 4
    & card ( FORM_PAYMENT ) = 3

END
