/* projeto_m_proB
 * Author: Ricar
 * Creation date: 01/06/2019
 */
MACHINE
    projeto_m_proB

SEES projeto_m_ctx
EXTENDS projeto_m

PROPERTIES
    card ( USER ) = 500
    & card ( STORE ) = 500
    & card ( PRODUCT ) = 500
    & card ( PROD_CATEGORY ) = 500
    & card ( ADDRESS ) = 500
    & card ( NAME ) = 500
    & card ( DATE ) = 500
    & card ( DESCRIPTION ) = 500
    & card ( COLOR ) = 500
    & card ( IMAGE ) = 500
    & card ( FORM_PAYMENT ) = 500

END
